version: '3'
services:
  app-fpm:
    container_name: 'app-fpm'
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./app:/srv/app

  app-caddy:
    container_name: 'app-caddy'
    depends_on: 
      - app-fpm
    build:
      context: .
      dockerfile: .docker/caddy/Dockerfile
    ports:
      - 8080:2015
    volumes:
      - ./.docker/caddy/data:${HOME}/.local/share/caddy/
