version: '3'
services:
  app:
    container_name: 'app-ppp'
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 8080:2015
    volumes:
      - ./app:/srv/app
      - ./.docker/app/caddy/data:${HOME}/.local/share/caddy/
