version: '3'
services:
  app:
    container_name: 'app-ppp'
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 8080:2015
      - 8081:2019
      - 8082:2016
      - 8083:84
    volumes:
      - ./app:/srv/app